
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neuroedge-go.fullname" . }}-prom-scrape
data:
  prometheus-scrape.yml: |-
    scrape_configs:
      - job_name: 'neuroedge-go'
        metrics_path: /metrics
        static_configs:
          - targets: ['{{ .Release.Name }}-{{ .Chart.Name }}:{{ .Values.service.port }}']
