
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuroedge-go.fullname" . }}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | default "" }}
  tls.key: {{ .Values.tls.key | default "" }}
