
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neuroedge-go.fullname" . }}
spec:
  selector:
    app: {{ include "neuroedge-go.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
