
version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.78.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318" # OTLP/HTTP
      - "4317:4317" # OTLP/gRPC
      - "55681:55681"
    volumes:
      - ./otel/collector-config.yaml:/etc/otel-collector-config.yaml:ro
