
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuroedge-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuroedge-go
  template:
    metadata:
      labels:
        app: neuroedge-go
    spec:
      containers:
        - name: neuroedge-go
          image: neuroedge-go:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/tls
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: neuroedge-tls
